services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
  postgres:
    image: postgres:13
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ogabrielnascr
      POSTGRES_PASSWORD: ogabrielnascr
      POSTGRES_DB: lumienergy-bills
    volumes:
      - pgdata:/var/lib/postgresql/data
  energify-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: energify-backend
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - .:/usr/src/
  # lumienergy-front:
  #   build:
  #     context: "./frontend"
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./frontend:/app
volumes:
  pgdata:
